#!/bin/sh

PCACHE="$HOME/.cache/vifm/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$PWD/$6")" | sha256sum)"
export PCACHE="${PCACHE%% *}"
XSHIFT=-1
YSHIFT=0
WADJUST=0
HADJUST=-1

pclear() {
	printf '{"action": "remove", "identifier": "vifm-preview"}\n' > "$FIFO_UEBERZUG"
}

image() {
		printf '{"action": "add", "identifier": "vifm-preview", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$(($2 + XSHIFT))" "$(($3 + YSHIFT))" "$(($4 + WADJUST))" "$(($5 + HADJUST))" "$6" > "$FIFO_UEBERZUG"
}

zipmontage() {
	CBZ_PREVIEW_TEMP=$(mktemp -d)
	zipinfo -1 "$1" | grep -iEe ".(jpeg|jpg|png)$" | shuf | head -9 | xargs -d "\n" -- unzip -q -d "${CBZ_PREVIEW_TEMP}" "$1"
	find "${CBZ_PREVIEW_TEMP}" -type f | sort -n | xargs -d "\n" -- feh -b trans -m -y 360 -E 240 -W 1280 -O "$2"
	rm -rf "${CBZ_PREVIEW_TEMP}"
}

main() {
    case "$1" in
        "clear")
			pclear "$@"
			;;
        "draw")
			FILE="$PWD/$6"
			image "$1" "$2" "$3" "$4" "$5" "$FILE"
			;;
        "video")
			[ ! -f "${PCACHE}.jpg" ] && \
				ffmpegthumbnailer -i "$6" -o "${PCACHE}.jpg" -s 0 -q 5
			image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
			;;
        "cbz")
			[ ! -f "${PCACHE}.png" ] && \
				zipmontage "$6" "${PCACHE}.png"
			image "$1" "$2" "$3" "$4" "$5" "$PCACHE.png"
			;;
        "epub")
			[ ! -f "$PCACHE" ] && \
				epub-thumbnailer "$6" "$PCACHE" 1024
			image "$1" "$2" "$3" "$4" "$5" "$PCACHE"
			;;
        "pdf")
			[ ! -f "${PCACHE}.jpg" ] && \
				pdftoppm -jpeg -f 1 -singlefile "$6" "$PCACHE"
			image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
			;;
        "djvu")
			[ ! -f "${PCACHE}.jpg" ] && \
				ddjvu -format=tiff -quality=90 -page=1 "$6" "$PCACHE.jpg"
			image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
			;;
        "audio")
			[ ! -f "${PCACHE}.jpg" ] && \
				ffmpeg -hide_banner -i "$6" "${PCACHE}.jpg" -y >/dev/null
			image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
			;;
        "font")
			[ ! -f "${PCACHE}.jpg" ] && \
				fontpreview -i "$6" -o "${PCACHE}.jpg"
			image "$1" "$2" "$3" "$4" "$5" "${PCACHE}.jpg"
			;;
        *)
    esac
}
main "$@"
